import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { GET_ALL_CATEGORIES, GET_ALL_CATEGORIES_SUCCESS } from "./../constans";

export default function Home() {
  const dispatch = useDispatch();
  const handleClick = () => {
    dispatch({ type: GET_ALL_CATEGORIES });
  };
  const { data } = useSelector((state) => state.CategoriesReducer);

  console.log("data", data);

  // console.log("data", data);
  // setInterval(() => {
  //   console.log("data", data);
  // }, 1000);

  return (
    <>
      <section>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Link href="/posts">
          <a>Posts</a>
        </Link>
        <div onClick={() => handleClick()}>Get categogies</div>
      </section>

      <section>
        <ul>
          {data.length > 0 &&
            data.map((dataItem) => {
              <li key={dataItem.id}>{dataItem.name}</li>;
            })}
        </ul>
      </section>
    </>
  );
}
