import Head from "next/head";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { GET_ALL_CATEGORIES } from "./../constans";

export default function Home() {
  const dispatch = useDispatch();
  const handleClick = () => {
    dispatch({ type: GET_ALL_CATEGORIES });
    console.log("data", data);
  };

  const { data } = useSelector((state) => state.CategoriesReducer);

  console.log("data", data);

  return (
    <section>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="posts">
        <a>Posts</a>
      </Link>
      <div onClick={handleClick()}>Get categogies</div>
    </section>
  );
}
