import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <section>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="posts">
        <a>Posts</a>
      </Link>
    </section>
  );
}
